services:
  qdrant:
    image: 'qdrant/qdrant:latest'
    ports:
      - '6333:6333'  # HTTP API port
      - '6334:6334'  # gRPC API port
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    ports:
      - '11434:11434'
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  qdrant_storage:
  ollama_data: